<?php
  function Take_Home_menu() {
    $items['Take_Home'] = array(
      'title' => "How much do you take home after all your city's inescapable costs?",
      'page callback' => 'drupal_get_form',
      'page arguments' => array('Take_Home_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );

    // $items['quiz_question_1'] = array(
    //   'page callback' => 'drupal_get_form',
    //   'page arguments' => array('quiz_form_one'),
    //   'access callback' => TRUE,
    //   'type' => MENU_CALLBACK,
    // );

    return $items;
  }

  function Take_Home_form() {
    $cities=db_query("SELECT * FROM col");
    $options=array();
    foreach($cities as $value){
      array_push($options, t($value->name));
    }
    sort($options);

    $form['cities'] = array(
      '#title' => "Which city do you live in?",
      '#type' => 'select',
      '#description' => t('Are you excited about this quiz?'),
      '#options' => $options,
      '#required' => TRUE,
    );

      $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'submit',
      );

        return $form;
  }

  // function get_gov(){
  //   $authorization = 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBUElfS0VZX01BTkFHRVIiLCJodHRwOi8vdGF4ZWUuaW8vdXNlcl9pZCI6IjU5MTlmMTlmZTkyMWMwMzY2NjZmMTMxZiIsImh0dHA6Ly90YXhlZS5pby9zY29wZXMiOlsiYXBpIl0sImlhdCI6MTQ5NDg3MjQ3OX0.grP0a9fG_4NdaOaRWk5H-lwG9XOfcgic8eUmhTPF7Tc';
  //   $curl = curl_init();
  //   curl_setopt_array($curl, array(
  //     CURLOPT_RETURNTRANSFER => 1,
  //     CURLOPT_URL => 'https://taxee.io/api/v2/state/2017/OR',
  //     CURLOPT_USERAGENT => 'SeanCodes'
  //   ));
  //   // curl_setopt($curl, CURLOPT_HEADER, 1);
  //   curl_setopt($curl, CURLOPT_HTTPHEADER,array('Content-Type: application/json', $authorization));
  //   $articles = curl_exec($curl);
  //   curl_close($curl);
  //   $stuff = json_decode($articles, true);
  //   echo '<pre>';
  //   var_dump($stuff);
  //   echo '</pre>';
  //
  //   return $stuff;
  // }
